### ISSUE TITLE
Log storage

### ISSUE THREAD

**Issue by leon** [mandubian/play-capistrano#1]
Capistrano symlinks the log directory to the shared directory.
After looking at the source code of capistrano, it looks like the log directory is hard coded, so we have no variable to set there.

Maybe we should set the directory in the log4j.properties files?

any suggestions?

**Comment by mandubian** [comment]
Do you mean the play log directory?
If yes, I create a conf/log4j.properties to put my log where I want.

**Comment by leon** [comment]
What is the correct path to put in the log4j.properties file?

/log/mydomain.com.log ?

On 14 okt 2011, at 16:13, Pascal Voitot
reply@reply.github.com
wrote:

**Comment by mandubian** [comment]
I put this in my log4j.properties:
log4j.appender.Rolling.File=log/myapp.log
and it writes them into PROJECT_PATH/log/myapp.log

**Comment by leon** [comment]
Great, thanks for the help..

Maybe you should put something under the documentation for your plugin about this, since otherwise cap play:logs doesn't work as expected.
