### ISSUE TITLE
Problem on first deployment

### ISSUE THREAD

**Issue by iammichiel** [mandubian/play-capistrano#4]
On first deployment, Capistrano is unabe to stop the current play application that is running. (as it is first deployment). 
Since `play stop myapp` returns an error if that app doesn't exist, Capistrano stops deployment and rolls back. 

A little check to see if an application exists would be a rapid fix. If I have a little time today or this weekend, I'll try to propose a fix.

**Comment by mandubian** [comment]
There is a PID file but the "cap stop" doesn't care at all... Generally, I stop manually the app before launching the deploy to be sure so I didn't remark this issue!

task :stop do
    run "#{play_path}/play stop #{app_path} --pid_file=#{app_pid}"
  end

Maybe simply verify there is the pid file could be enough?

Thks
Pascal

**Comment by mandubian** [comment]
Hi,

Could you try last draft version of play-capistrano 1.0.1 (available on play module repo) ?
I added a new stop.sh script which tries to find the PID file before trying to stop the server.
It prevents the first deployment stop error!

Pascal

**Comment by iammichiel** [comment]
Re, 

Great works for me! Great job and thanks for your quick reaction!

**Comment by mandubian** [comment]
let's close this issue and I'll try to deliver a new official version of the module to play site!
